import { Button } from '@/components/Button';
import { Screen } from '@/components/Screen';
import { useApp } from '@/context/AppContext';
import { approveMinutes, loadMinutes, loadSessions, publishMinutes, saveMinutes, submitMinutesForReview } from '@/lib/solRepository';
import { useManagerAudioTranscription } from '@/lib/useManagerAudioTranscription';
import { colors } from '@/theme/colors';
import { Feather } from '@expo/vector-icons';
import { useEffect, useMemo, useState } from 'react';
import { Platform, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';

type Feedback={type:'success'|'error';text:string}|null;

export default function ManagerMinutesScreen(){
  const{lodge,lodgeMembers,membership}=useApp();
  const nativeVoice=useManagerAudioTranscription('MINUTES');
  const[sessions,setSessions]=useState<any[]>([]);const[history,setHistory]=useState<any[]>([]);
  const[selectedSessionId,setSelectedSessionId]=useState('');const[meetingDate,setMeetingDate]=useState(new Date().toISOString().slice(0,10));
  const[sessionLabel,setSessionLabel]=useState('Sessão ordinária');const[location,setLocation]=useState('');
  const[matters,setMatters]=useState('');const[decisions,setDecisions]=useState('');const[pendingItems,setPendingItems]=useState('');const[closingNotes,setClosingNotes]=useState('');
  const[transcript,setTranscript]=useState('');const[savedMinutes,setSavedMinutes]=useState<any|null>(null);const[audience,setAudience]=useState('ALL');
  const[webListening,setWebListening]=useState(false);const[busy,setBusy]=useState<string|null>(null);const[feedback,setFeedback]=useState<Feedback>(null);

  const isMaster=membership?.role==='WORSHIPFUL_MASTER';
  const selectedSession=sessions.find((s)=>s.id===selectedSessionId);
  const attendance=useMemo(()=>{const ids=(selectedSession?.lodge_attendance??[]).map((x:any)=>x.member_id);return lodgeMembers.filter((m)=>ids.includes(m.id));},[selectedSession,lodgeMembers]);
  const listening=Platform.OS==='web'?webListening:nativeVoice.isRecording;

  const reload=async()=>{if(!lodge)return;try{const[s,h]=await Promise.all([loadSessions(lodge.id),loadMinutes(lodge.id)]);setSessions(s??[]);setHistory(h??[]);}catch(e){setFeedback({type:'error',text:errorMessage(e)});}};
  useEffect(()=>{void reload();},[lodge?.id]);

  const selectSession=(s:any)=>{setSelectedSessionId(s.id);setMeetingDate(String(s.starts_at).slice(0,10));setSessionLabel(s.title||'Sessão ordinária');setLocation(s.location||'');setSavedMinutes(null);};

  const startVoice=async()=>{
    setFeedback(null);
    if(Platform.OS!=='web'){
      try{await nativeVoice.start();setFeedback({type:'success',text:'Gravando a ata. Fale naturalmente; ao terminar, toque em “Parar e transcrever”.'});}catch(e){setFeedback({type:'error',text:errorMessage(e)});}return;
    }
    const w=globalThis as any;const SpeechRecognition=w.SpeechRecognition||w.webkitSpeechRecognition;
    if(!SpeechRecognition){setFeedback({type:'error',text:'Este navegador não oferece reconhecimento de voz. Use Chrome/Edge ou digite o relato.'});return;}
    const recognition=new SpeechRecognition();recognition.lang='pt-BR';recognition.interimResults=true;recognition.continuous=true;let finalText=transcript;
    recognition.onstart=()=>setWebListening(true);recognition.onend=()=>setWebListening(false);recognition.onerror=(e:any)=>{setWebListening(false);setFeedback({type:'error',text:`Microfone: ${e?.error??'não disponível'}`});};
    recognition.onresult=(event:any)=>{let interim='';for(let i=event.resultIndex;i<event.results.length;i++){const piece=event.results[i][0]?.transcript??'';if(event.results[i].isFinal)finalText=`${finalText} ${piece}`.trim();else interim+=piece;}setTranscript(`${finalText}${interim?` ${interim}`:''}`.trim());};
    recognition.start();(globalThis as any).__connexioMinutesRecognition=recognition;
  };

  const stopVoice=async()=>{
    setFeedback(null);
    if(Platform.OS==='web'){const r=(globalThis as any).__connexioMinutesRecognition;if(r?.stop)r.stop();setWebListening(false);return;}
    setBusy('transcribe');
    try{const text=await nativeVoice.stopAndTranscribe();setTranscript((old)=>`${old} ${text}`.trim());setFeedback({type:'success',text:'Áudio transcrito pelo Staff/Whisper. Agora toque em “Estruturar ditado” e revise.'});}
    catch(e){setFeedback({type:'error',text:errorMessage(e)});}finally{setBusy(null);}
  };

  const structureTranscript=()=>{if(!transcript.trim()){setFeedback({type:'error',text:'Dite ou escreva primeiro o relato da sessão.'});return;}const s=structureMinutes(transcript);setMatters(s.matters);setDecisions(s.decisions);setPendingItems(s.pendingItems);setClosingNotes(s.closingNotes);setFeedback({type:'success',text:'Ditado organizado. Revise antes de salvar.'});};
  const generated=buildGeneratedText({lodgeName:lodge?.name??'Loja',meetingDate,sessionLabel,location,attendanceNames:attendance.map((m)=>m.name),matters,decisions,pendingItems,closingNotes});

  const save=async()=>{if(!lodge||!meetingDate.trim()||!sessionLabel.trim()){setFeedback({type:'error',text:'Informe data e sessão.'});return;}setBusy('save');try{const row=await saveMinutes(lodge.id,{meetingDate:meetingDate.trim(),sessionLabel:sessionLabel.trim(),location:location.trim(),matters:matters.trim(),decisions:decisions.trim(),pendingItems:pendingItems.trim(),closingNotes:closingNotes.trim(),sessionId:selectedSessionId||null,transcript:transcript.trim(),generatedText:generated,attendanceSnapshot:attendance.map((m)=>({id:m.id,name:m.name}))});setSavedMinutes(row);await reload();setFeedback({type:'success',text:'Ata salva como rascunho.'});}catch(e){setFeedback({type:'error',text:errorMessage(e)});}finally{setBusy(null);}};
  const sendReview=async()=>{if(!savedMinutes?.id)return;setBusy('review');try{await submitMinutesForReview(savedMinutes.id);setSavedMinutes({...savedMinutes,status:'IN_REVIEW'});await reload();setFeedback({type:'success',text:'Ata enviada ao Venerável.'});}catch(e){setFeedback({type:'error',text:errorMessage(e)});}finally{setBusy(null);}};
  const approve=async()=>{if(!savedMinutes?.id)return;setBusy('approve');try{await approveMinutes(savedMinutes.id);setSavedMinutes({...savedMinutes,status:'APPROVED'});await reload();setFeedback({type:'success',text:'Ata aprovada.'});}catch(e){setFeedback({type:'error',text:errorMessage(e)});}finally{setBusy(null);}};
  const publish=async()=>{if(!savedMinutes?.id)return;setBusy('publish');try{await publishMinutes(savedMinutes.id,audience);setSavedMinutes({...savedMinutes,status:'PUBLISHED'});await reload();setFeedback({type:'success',text:'Ata publicada na Central da Loja.'});}catch(e){setFeedback({type:'error',text:errorMessage(e)});}finally{setBusy(null);}};

  return <Screen contentStyle={styles.content}>
    <View style={styles.header}><Text style={styles.eyebrow}>GESTOR PRO · SECRETARIA</Text><Text style={styles.title}>Atas Inteligentes por Voz</Text><Text style={styles.subtitle}>Selecione a sessão, fale naturalmente, revise a estrutura e só então salve, envie ao Venerável ou publique.</Text></View>
    {feedback?<View style={[styles.feedback,feedback.type==='error'?styles.feedbackError:styles.feedbackSuccess]}><Feather name={feedback.type==='error'?'alert-circle':'check-circle'} size={18} color={feedback.type==='error'?colors.danger:colors.success}/><Text style={styles.feedbackText}>{feedback.text}</Text></View>:null}

    <View style={styles.card}><Text style={styles.sectionTitle}>1. Sessão</Text><View style={styles.chips}>{sessions.slice(0,8).map((s)=><Pressable key={s.id} onPress={()=>selectSession(s)} style={[styles.chip,selectedSessionId===s.id&&styles.chipActive]}><Text style={[styles.chipText,selectedSessionId===s.id&&styles.chipTextActive]}>{s.title} · {new Date(s.starts_at).toLocaleDateString('pt-BR')}</Text></Pressable>)}</View><View style={styles.row}><TextInput value={meetingDate} onChangeText={setMeetingDate} placeholder="AAAA-MM-DD" placeholderTextColor={colors.textMuted} style={[styles.input,styles.flex]}/><TextInput value={sessionLabel} onChangeText={setSessionLabel} placeholder="Sessão" placeholderTextColor={colors.textMuted} style={[styles.input,styles.flex]}/></View><TextInput value={location} onChangeText={setLocation} placeholder="Local" placeholderTextColor={colors.textMuted} style={styles.input}/>{selectedSession?<Text style={styles.helper}>Presenças: {attendance.length?attendance.map((m)=>m.name).join(', '):'nenhuma registrada ainda'}</Text>:null}</View>

    <View style={styles.voiceCard}><View style={styles.voiceHead}><View style={styles.voiceIcon}><Feather name="mic" size={28} color={colors.background}/></View><View style={styles.flex}><Text style={styles.sectionTitle}>2. Gravar / ditar ata</Text><Text style={styles.helper}>{Platform.OS==='web'?'A Web usa reconhecimento do navegador.':'No Android o áudio é gravado no aparelho e transcrito pelo Staff/Whisper.'}</Text></View></View><TextInput value={transcript} onChangeText={setTranscript} multiline placeholder="A transcrição aparecerá aqui..." placeholderTextColor={colors.textMuted} style={[styles.input,styles.transcript]}/><View style={styles.row}>{!listening?<Button label="Gravar ata" onPress={()=>void startVoice()} style={styles.flex}/>:<Button label="Parar e transcrever" onPress={()=>void stopVoice()} style={styles.flex}/>}<View style={styles.recordState}><Feather name={listening?'radio':'clock'} size={15} color={listening?colors.gold:colors.textMuted}/><Text style={styles.helper}>{listening&&Platform.OS!=='web'?`${Math.round(nativeVoice.durationMillis/1000)}s`:nativeVoice.transcribing||busy==='transcribe'?'Transcrevendo…':listening?'Ouvindo…':'Pronto'}</Text></View></View><Button label="Estruturar ditado" variant="secondary" disabled={!transcript.trim()} onPress={structureTranscript}/></View>

    <View style={styles.card}><Text style={styles.sectionTitle}>3. Revisar</Text><Area label="Assuntos tratados" value={matters} onChangeText={setMatters}/><Area label="Deliberações e votações" value={decisions} onChangeText={setDecisions}/><Area label="Pendências, responsáveis e prazos" value={pendingItems} onChangeText={setPendingItems}/><Area label="Encerramento" value={closingNotes} onChangeText={setClosingNotes}/><Button label="Salvar rascunho" loading={busy==='save'} onPress={()=>void save()}/></View>
    <View style={styles.preview}><Text style={styles.previewTitle}>Prévia institucional</Text><Text selectable style={styles.previewText}>{generated}</Text></View>

    {savedMinutes?<View style={styles.card}><Text style={styles.sectionTitle}>4. Destino</Text><Text style={styles.status}>Status: {statusLabel(savedMinutes.status)}</Text><View style={styles.row}><Button label="Enviar ao Venerável" variant="secondary" loading={busy==='review'} onPress={()=>void sendReview()} style={styles.flex}/>{isMaster?<Button label="Aprovar" variant="secondary" loading={busy==='approve'} onPress={()=>void approve()} style={styles.flex}/>:null}</View><Text style={styles.label}>Publicar para</Text><View style={styles.chips}>{[['ALL','Todos'],['APPRENTICE','Aprendizes'],['FELLOWCRAFT','Companheiros'],['MASTER','Mestres'],['LEADERSHIP','Liderança']].map(([v,l])=><Pressable key={v} onPress={()=>setAudience(v)} style={[styles.chip,audience===v&&styles.chipActive]}><Text style={[styles.chipText,audience===v&&styles.chipTextActive]}>{l}</Text></Pressable>)}</View><Button label="Publicar na Central da Loja" loading={busy==='publish'} onPress={()=>void publish()}/></View>:null}

    <View style={styles.card}><Text style={styles.sectionTitle}>Atas recentes</Text>{history.slice(0,6).map((item)=><Pressable key={item.id} onPress={()=>{setSavedMinutes(item);setMeetingDate(item.meeting_date);setSessionLabel(item.session_label);setLocation(item.location??'');setMatters(item.matters??'');setDecisions(item.decisions??'');setPendingItems(item.pending_items??'');setClosingNotes(item.closing_notes??'');setTranscript(item.transcript??'');setSelectedSessionId(item.session_id??'');}} style={styles.historyItem}><Feather name="file-text" size={17} color={colors.gold}/><View style={styles.flex}><Text style={styles.historyTitle}>{item.session_label}</Text><Text style={styles.helper}>{new Date(`${item.meeting_date}T12:00:00`).toLocaleDateString('pt-BR')} · {statusLabel(item.status)}</Text></View><Feather name="chevron-right" size={18} color={colors.textMuted}/></Pressable>)}{!history.length?<Text style={styles.helper}>Nenhuma ata registrada.</Text>:null}</View>
  </Screen>;
}

function structureMinutes(raw:string){const sentences=raw.replace(/\s+/g,' ').split(/(?<=[.!?])\s+/).map((s)=>s.trim()).filter(Boolean);const decisions:string[]=[],pending:string[]=[],closing:string[]=[],matters:string[]=[];for(const s of sentences){const l=s.toLowerCase();if(/aprovad|rejeitad|deliber|votaç|votacao|decid|unanimidade|maioria/.test(l))decisions.push(s);else if(/responsável|responsavel|encarregado|pendência|pendencia|prazo|até o dia|ate o dia/.test(l))pending.push(s);else if(/encerr|finaliz|nada mais havendo/.test(l))closing.push(s);else matters.push(s);}return{matters:matters.join('\n')||raw.trim(),decisions:decisions.join('\n'),pendingItems:pending.join('\n'),closingNotes:closing.join('\n')};}
function buildGeneratedText(i:{lodgeName:string;meetingDate:string;sessionLabel:string;location:string;attendanceNames:string[];matters:string;decisions:string;pendingItems:string;closingNotes:string}){const date=i.meetingDate?new Date(`${i.meetingDate}T12:00:00`).toLocaleDateString('pt-BR'):'—';return[`ATA · ${i.lodgeName}`,`${i.sessionLabel} · ${date}${i.location?` · ${i.location}`:''}`,`Presentes: ${i.attendanceNames.length?i.attendanceNames.join(', '):'a confirmar'}`,`Assuntos tratados\n${i.matters||'—'}`,`Deliberações e votações\n${i.decisions||'—'}`,`Pendências, responsáveis e prazos\n${i.pendingItems||'—'}`,`Encerramento\n${i.closingNotes||'—'}`].join('\n\n');}
function statusLabel(s:string){return({DRAFT:'Rascunho',IN_REVIEW:'Em revisão',APPROVED:'Aprovada',PUBLISHED:'Publicada',ARCHIVED:'Arquivada'} as Record<string,string>)[s]??s;}
function Area({label,value,onChangeText}:{label:string;value:string;onChangeText:(v:string)=>void}){return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput value={value} onChangeText={onChangeText} multiline placeholder={label} placeholderTextColor={colors.textMuted} style={[styles.input,styles.area]}/></View>;}
function errorMessage(e:unknown){if(e instanceof Error)return e.message;if(e&&typeof e==='object'&&'message'in e)return String((e as any).message);return'Tente novamente.';}
const styles=StyleSheet.create({content:{paddingTop:22,gap:18},header:{gap:6},eyebrow:{color:colors.gold,fontSize:10,fontWeight:'900',letterSpacing:1.2},title:{color:colors.cream,fontSize:28,fontWeight:'900'},subtitle:{color:colors.textMuted,fontSize:13,lineHeight:19},feedback:{flexDirection:'row',gap:9,padding:13,borderRadius:14,borderWidth:1},feedbackError:{borderColor:colors.danger,backgroundColor:'rgba(245,141,141,.08)'},feedbackSuccess:{borderColor:colors.success,backgroundColor:'rgba(109,207,151,.08)'},feedbackText:{flex:1,color:colors.text,fontSize:11,lineHeight:17},card:{gap:12,padding:16,borderRadius:18,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border},voiceCard:{gap:12,padding:17,borderRadius:20,backgroundColor:'rgba(209,174,87,.08)',borderWidth:1,borderColor:colors.gold},voiceHead:{flexDirection:'row',alignItems:'center',gap:12},voiceIcon:{width:54,height:54,borderRadius:17,backgroundColor:colors.gold,alignItems:'center',justifyContent:'center'},sectionTitle:{color:colors.cream,fontSize:15,fontWeight:'900'},row:{flexDirection:'row',gap:9,alignItems:'center',flexWrap:'wrap'},flex:{flex:1},field:{gap:6},label:{color:colors.text,fontSize:11,fontWeight:'800'},input:{minHeight:48,borderRadius:13,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surfaceRaised,color:colors.text,paddingHorizontal:13},area:{minHeight:90,paddingTop:12,textAlignVertical:'top'},transcript:{minHeight:145,paddingTop:12,textAlignVertical:'top'},chips:{flexDirection:'row',flexWrap:'wrap',gap:7},chip:{paddingHorizontal:10,paddingVertical:8,borderRadius:999,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surfaceRaised},chipActive:{borderColor:colors.gold,backgroundColor:'rgba(209,174,87,.12)'},chipText:{color:colors.textMuted,fontSize:9,fontWeight:'800'},chipTextActive:{color:colors.goldSoft},helper:{color:colors.textMuted,fontSize:10,lineHeight:15},recordState:{flexDirection:'row',alignItems:'center',gap:6,minWidth:90},preview:{padding:16,borderRadius:18,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.gold,gap:9},previewTitle:{color:colors.goldSoft,fontSize:13,fontWeight:'900'},previewText:{color:colors.textMuted,fontSize:11,lineHeight:18},status:{color:colors.goldSoft,fontSize:11,fontWeight:'900'},historyItem:{flexDirection:'row',alignItems:'center',gap:10,padding:11,borderRadius:13,backgroundColor:colors.surfaceRaised},historyTitle:{color:colors.text,fontSize:12,fontWeight:'900'}});
